#ifndef RUNTIMEPROFILE_STEADYCLOCKPROFILER_HPP
#define RUNTIMEPROFILE_STEADYCLOCKPROFILER_HPP

#include "Profile.hpp"

namespace Profile {
    using steady_clock_record = Profile::RecordProfile<std::chrono::steady_clock>;
}

#define STEADY_CLOCK_PROFILE_SCOPE_LINE_1(LOGGER, VAR, NAME, LINE) Profile::steady_clock_record VAR##LINE##__{LOGGER, NAME}
#define STEADY_CLOCK_PROFILE_SCOPE_LINE(LOGGER, VAR, NAME, LINE) STEADY_CLOCK_PROFILE_SCOPE_LINE_1(LOGGER, VAR, NAME, LINE)
#define STEADY_CLOCK_PROFILE_SCOPE(LOGGER, NAME) STEADY_CLOCK_PROFILE_SCOPE_LINE(LOGGER, profileTimer, NAME, __LINE__)
#define STEADY_CLOCK_PROFILE_FUNCTION(LOGGER) STEADY_CLOCK_PROFILE_SCOPE(LOGGER, __FUNCTION__)

#endif// RUNTIMEPROFILE_STEADYCLOCKPROFILER_HPP
